### ISSUE TITLE
Add doc and video links to help modal

### ISSUE THREAD

**Issue by blaino** [ozone-development/ozp-hud#102]
Implement same fix as for center (https://huboard.com/ozone-development/ozp-center#/issues/86301820). Needs to show the name of the link as opposed the destination of the link.

**Comment by mparizernc** [comment]
Verified in all the browsers in Develop that the labels are shown instead of links and verified they open to the proper links.

**Comment by mparizernc** [comment]
Verified in all the browsers in Staging that the labels are shown instead of links and verified they open to the proper links.
