### ISSUE TITLE
Make folder view look like mockup

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-hud#105]
Make the folder view look like the mockups created which is consistent with modals from webtop.
![hud_foldershare_1_modal](https://raw.githubusercontent.com/ozone-development/ozp-documentation/master/mockups/hud/HUD_FolderShare_1_modal.png)

**Comment by jal-vsi** [comment]
Passed in IE9/11, CH, and FF on Develop environment

**Comment by jal-vsi** [comment]
Passed in Master (IE9/11, FF, CH).
