### ISSUE TITLE
Make modal for folder sharing

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-hud#106]
When a user clicks share folder, make this modal appear

![hud_foldershare_1_modal](https://raw.githubusercontent.com/ozone-development/ozp-documentation/master/mockups/hud/HUD_FolderShare_2_lookup.png)

**Comment by hoganmaps** [comment]
![hud_foldershare_beta_2_url](https://cloud.githubusercontent.com/assets/2993032/9995597/eb353efe-6050-11e5-9ee5-c4d0d4523591.png)

going with a shareable link until backend supports sharing folders directly with users

**Comment by tonyalletag** [comment]
OBE - being tracked in #137
