### ISSUE TITLE
App won't launch from HUD into Webtop (IE9/11)

### ISSUE THREAD

**Issue by jal-vsi** [ozone-development/ozp-hud#122]
Apps in HUD won't launch into Webtop when using IE 9 or IE 11 after the first launch.  Multiple launches from HUD into Webtop do work in FF24 and CH36.

**Comment by hoganmaps** [comment]
closing this - this is all on the webtop side. I will open this ticket with the same text in webtops bugs

**Comment by hoganmaps** [comment]
which you already had: [webtop 625](https://github.com/ozone-development/ozp-webtop/issues/625)
