### ISSUE TITLE
Implement Share Folder modal

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-hud#123]
Skip the copy button part. Text should be 'Copy and paste this URL to share this folder with others'

![hud_foldershare_beta_2_url_1024](https://cloud.githubusercontent.com/assets/2993032/9632954/0df01d0e-5158-11e5-8da9-1efcf77e59d2.png)

**Comment by jal-vsi** [comment]
Passed test in Develop (IE9/11, CH, FF).

**Comment by jal-vsi** [comment]
Passed test in Master (IE9/11, CH, FF).  Create a folder in HUD, copy URL, paste in browser (or email to someone), folder/apps are active, new folder is in Webtop.
