### ISSUE TITLE
Contact Modal

### ISSUE THREAD

**Issue by KageRyu7** [ozone-development/ozp-hud#126]
A contact modal that will contain links to help, feature requests, feedback, and social media. This is a solution to the original issue here...
https://github.com/ozone-development/ozp-center/issues/348

This will also be in...
ozp-react-commons
https://github.com/ozone-development/ozp-react-commons/issues/26
Webtop
https://github.com/ozone-development/ozp-webtop/issues/635

**Comment by mparizernc** [comment]
I have tested this locally in IE9,11, Firefox and Chrome and found no issues. Ready for testing on master.

**Comment by jal-vsi** [comment]
Tested/Passed in Master (IE9/11, FF, CH).  The links (help, chirp, pin, chat, blog) go to an undefined web (has to be defined/configured on the high side).  The mail links (contact help, give feedback, submit a request) go to Outlook (has to be configured on the high side).

**Comment by mparizernc** [comment]
Tested this in staging against IE10, FF and Chrome. All of the links worked as expected.  There is an issue in IE10 that causes an email to not work as expected on staging.  That is outside of the scope of this ticket.
