### ISSUE TITLE
Shared Folder - "Open all in new dashboard" should work in both IE and Firefox

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-hud#135]
Please fix "Open all in new dashboard" button/link so that it works in IE and Firefox.  

Also fix styling so that it matches that of the "Get Shareable Link" button.
Currently the mouse turns into a text cursor when hovering over the words in the "Open..." button.  This does not look right.

**Comment by tonyalletag** [comment]
OBE - Menu Option has been removed
