### ISSUE TITLE
CHROME only - Copying a shareable link wont stay highlighted long enough to share.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-hud#168]
STR-
Bookmark three apps from Center
Go to HUD
Drag the two apps on top of the third app in order to create a folder with all three apps
Open folder
Get shareable link
Click on the url
RESULTS - The link will highlight for a second then unhighlight really fast so the user can never actually copy it.
EXPECTED RESULTS - When the user clicks on the URL it should highlight and stay highlighted.

**Comment by akonsowski** [comment]
It looks like it is working to me. Is it possible you double clicked the link?

**Comment by akonsowski** [comment]
never mind i was able to reproduce this issue, if you don't save the name of the folder first and try to go into it
