### ISSUE TITLE
HUD always shows "No Bookmarks" on initial load

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-hud#64]
The HUD page loads and displays "No Bookmarks" then it retrieves data and refreshes and displays any apps that are bookmarked.

Suggest changing initial load of HUD page to say "Loading Data" then display apps that are bookmarked. If nothing is bookmarked display "No Bookmarks"

**Comment by sdeighan** [comment]
![hud_loading](https://cloud.githubusercontent.com/assets/7987446/7167439/f6906b20-e382-11e4-9259-2d1c01e871af.png)

**Comment by mparizernc** [comment]
All Browsers

Verified that the loader is loading when the HUD is waiting for log on.

**Comment by jloveland18** [comment]
tested on staging 0.7.4

All Browsers

Verified that the loader circles when the HUD waits for log on.
