### ISSUE TITLE
Bookmarks - If DB is down, HUD displays "no apps"

### ISSUE THREAD

**Issue by jloveland18** [ozone-development/ozp-hud#78]
If the Database is down, but Platform is still up, HUD Displays the default screen. Let's ignore the fact that the default screen says you have no apps. Instead, let's Overwrite that message with an error message.

**Comment by wski** [comment]
Right now it shows a loading indicator, will need to add a "Could no reach database" or something similar

**Comment by mparizernc** [comment]
@kgordon-1 I tested this locally. I disconnected my DB, loaded the HUD and after about 20 seconds a message pops up below the spinner stating "The request is taking longer than usual, there may be a serverside issue."

**Comment by kgordon-1** [comment]
For now, this will stay open until further investigation after IOB.  Because of the issue Mike found.  See above comment.
