### ISSUE TITLE
Bookmarks - "Get help" in listing menu

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-hud#79]
In HUD, click on the drop down arrow and select Get help.  For now it displays Resource tab.

**Comment by mparizernc** [comment]
That is the intent.  The point of this was to direct the user to the Resource tab in the store so that they can click any documentation links for the listing or contact someone.

**Comment by sdeighan** [comment]
Feature performing as designed - it just looks very empty due to the limited dummy data. The listings should be populated with links to help documentation and contact information for users to leverage when they have a problem.
