### ISSUE TITLE
OzoneConfig - Update the file to match Webtop & Center

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-hud#80]
Add IWC to match Webtop and Center

**Comment by sdeighan** [comment]
Added in React-commons

**Comment by mparizernc** [comment]
Verified that the OzoneConfig.js has the same links across the products.

**Comment by mparizernc** [comment]
I pulled the builds from jenkins that will go to Production and verified that the OzoneConfig.js has the same links across the products.
