### ISSUE TITLE
Place apps in Folders in HUD, unable to preview apps or delete folder

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-hud#87]
Bookmark at least 3 apps and review apps in HUD.
Put the apps into a folder.  Now try and display one of the apps
Or move them out of the folder.
Unable to select apps in the folder for preview and unable to take apps out of folder environment or delete folder.

**Comment by clarkjefcoat** [comment]
@kgordon-1 Was this bug fixed when #88 was addressed or does this ticket refer to something different?

**Comment by tonyalletag** [comment]
This is working in staging and production
