### ISSUE TITLE
Folders - When opening, will not finish loading contents

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-hud#88]
In Develop -
If you create a folder of applications, the folder will not display contents (probably being that it won't finish loading) until I refresh the page or switch tabs

![hud_newfolder_bugindevelop](https://cloud.githubusercontent.com/assets/7987446/7657348/389bf29e-faff-11e4-8da2-f2271b6f8c3b.png)

**Comment by kgordon-1** [comment]
This is what I see

**Comment by kgordon-1** [comment]
Created 2 folders with 3 or 4 apps.  Removed one of the folders by removing the apps.  Able to perform upper right menu functions.  like launch to webtop etc.  all of them.  However, Need to refresh to get scroll bar.
