### ISSUE TITLE
Application Library widget

### ISSUE THREAD

**Issue by stephanieerin** [ozone-development/ozp-hud#91]

**Comment by mparizernc** [comment]
This has been tested but is waiting to be merged into master. When it does it will need to be tested in develop again.

**Comment by mparizernc** [comment]
Tests:

This widget should work the same way the HUD worked before it was made into widgets:
* Verify Bookmarked listings appear
* Verify dragging listings to change order
* Verify dragging listings on to each other to create folders
 * Verify renaming folders 
 * Verify opening folders
 * Verify dragging listings out of folders
* Verify listing menus 
  * Open a listing in a new tab
  * Open a listing in the webtop
  * Verify opening the listing contact info/help opens the center to the resources page
        * Verify removing the bookmark
* Verify the setting for opening in a new tab/webtop works when you double click the listing
* Resize the widget in the hud
* Move the widget to different locations on the hud

**Comment by clarkjefcoat** [comment]
Temporarily moving back to "Working".  "Resolved" should mean that it is available on our testing servers.

**Comment by tonyalletag** [comment]
this is on hold
