### ISSUE TITLE
My Listings widget

### ISSUE THREAD

**Issue by stephanieerin** [ozone-development/ozp-hud#92]

**Comment by mparizernc** [comment]
This has been tested but is waiting to be merged into master. When it does it will need to be tested in develop again.

**Comment by mparizernc** [comment]
Testing:

My Listings
---------------
* Verify that there is a My Listings widget in the HUD if you own listings
 * Verify status counts are correct
 * Verify only listings you own appear on the widget
 * Verify that Recent Activity shows the 25 most recent activity only for listings you  own
 * Very the Listing Management link takes you to the Center's Recent Activity
 * Verify that Listing links open the listing detailed view
 * Verify Activity details can be expanded when they exist
* Verify that you resize the widget
* Verify that you can move the widget to different locations in the HUD

AML Steward Listings
---------------------------
* Verify that this widget only appears for the AML Steward(s)
 * Verify status counts are correct and for ALL listings in the system
 * Verify that Recent Activity shows the 25 most recent activity for all listings in the system
 * Very the Listing Management link takes you to the Center's Recent Activity
 * Verify that Listing links open the listing detailed view
 * Verify Activity details can be expanded when they exist
* Verify that you resize the widget
* Verify that you can move the widget to different locations in the HUD

Org Steward Listings
---------------------------
* Verify that this widget only appears for the Org Steward(s) it is the same widget as the AML Steward so counts will appear for both if you are an AML Steward and Org Steward
 * Verify status counts are correct and for listings in the system that you are the Org Steward for (if you are steward of two Orgs the counts will be combined)
 * Verify being Org Steward for multiple orgs shows the correct counts and activity
 * Verify that Recent Activity shows the 25 most recent activity for all listings you  are the Org for
 * Very the Listing Management link takes you to the Center's Recent Activity
 * Verify that Listing links open the listing detailed view
 * Verify Activity details can be expanded when they exist
* Verify that you resize the widget
* Verify that you can move the widget to different locations in the HUD

Scenarios for showing the widgets
----------------------------------------
* User
 * Do not own listings - no listing widgets will appear
 * Own listings - My Listings widget will appear
* Org Steward
 * Do not own listings - only the Org Steward widget will appear
 * Own listings - the Org Steward and My Listings widgets will appear
* AML Steward
 * Do not own listings - only the AML Steward widget will appear
 * Own listings - the AML Steward and My Listings widgets will appear
 * Are content steward - AML and Org Steward counts will appear in the widget

**Comment by clarkjefcoat** [comment]
Temporarily moving back to "Working".  "Resolved" should mean that it is available on our testing servers.

**Comment by tonyalletag** [comment]
this is on hold
