### ISSUE TITLE
Bookmarks - Rename bookmarks to favorites

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-hud#99]
Renaming Bookmarks to Favorites would be consistent with our existing marketing materials.  (If this is moved out of backlog please add tickets to webtop and center to change their dropdown menus to say Favorites).

**Comment by sdeighan** [comment]
We had a very detailed discussion about whether these would be "Bookmarks" or "Favorites" at the beginning of this project. In the end, it was decided that we would use "Bookmarks" for now, reserving "Favorites" for future functionality. If users have a lot of bookmarks, a second tier of organization will be added called "Favorites" and those would appear in many places as a small / quick set of the apps and allow easy, speedy access.
All of the icons and wording ("Bookmarks" and "Your Library") were chosen accordingly. If we need to switch it to "Favorites" it will be very difficult to implement and will probably necessitate another terminology change.

Also, I strongly disagree with changing thoroughly thought-out decisions and re-doing all the terminology and iconography of the platform to reflect marketing materials which should be describing the platform.

**Comment by clarkjefcoat** [comment]
Thanks, Sarah.  Tony just told me that we had already had this conversation.

This request came from program management.  We'll see what we can do to convince them this isn't the correct approach.

I'm adding a "User Submitted" tag to any issues that were reported by users (or management) of the system.  This does not mean that we have to accept all of these requests, but we do need a way to prove that we received their request and considered it.

**Comment by tonyalletag** [comment]
I agree we should not implement this at this time.
